baseurl = "/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "STA 112FS"
theme = "material"
#disqusShortname = ""
# googleAnalytics = ""
paginate = 7
relativeurls = true
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Mine Cetinkaya-Rundel"
  bio = ""
  job = "Associate Professor of the Practice"
  location = "Duke University"
  gravatarEmail = "mine@stat.duke.edu"
  # Your profile picture
#  picture = ""
  twitter = "minebocek"
 
# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
#[[menu.main]]
#  weight = 2
#  identifier = "modules"
#  name = "Modules"
#  pre = "<i class=\"material-icons\">dashboard</i>"
#  url = "/modules"  
[[menu.main]]
  weight = 3
  identifier = "tools"
  name = "Tools"
  pre = "<i class=\"material-icons\">build</i>"
  url = "/tools"
[[menu.main]]
  weight = 4
  identifier = "syllabus"
  name = "Syllabus"
  pre = "<i class=\"material-icons\">date_range</i>"
  url = "/syllabus"
[[menu.main]]
  weight = 5
  identifier = "policies"
  name = "Policies"
  pre = "<i class=\"material-icons\">gavel</i>"
  url = "/policies"

[[menu.footer]]
  weight = 1
  identifier = "Duke"
  name = "Duke StatSci"
  pre = "<i class=\"button-icon fa fa-2x fa-map-marker\"></i>"
  url = "http://stat.duke.edu/"
[[menu.footer]]
  weight = 2
  name = "R/RStudio"
  pre = "<i class=\"icon-rlogo\" style=\"font-size:150%\"></i>"
  url = "https://vm-manage.oit.duke.edu/"
[[menu.footer]]
  weight = 3
  identifier = "GitHub"
  name = "GitHub"
  pre = "<i class=\"button-icon fa fa-2x fa-github\"></i>"
  url = "https://github.com/Sta112-F17/"
[[menu.footer]]
  weight = 4
  identifier = "Slack"
  name = "Slack"
  pre = "<i class=\"button-icon fa fa-2x fa-slack\"></i>"
  url = "https://sta112f17.slack.com/messages"


[params]
  dateFormat = "January 2, 2006"
  background = "http://www2.stat.duke.edu/courses/Fall17/sta112.01/img/mugesketch.png"
  favicon = "img/favicon.ico"
